#pragma once
#include "AgentBase.hpp"
#include <sstream>

/**
 * @brief Development Agent specialized in code generation with production-grade enforcement
 *
 * This agent is specifically designed for development tasks and enforces
 * the AI Behavior Mandate for all code generation, ensuring production-quality output.
 */
class DevelopmentAgent : public AgentBase {
public:
  explicit DevelopmentAgent() : AgentBase("DevelopmentAgent") {
    initializeBehaviorPolicy();
  }

  std::string getTaskContext() const override {
    return "code";
  }

protected:
  std::string executeTask(const std::string& input) override {
    // Analyze the development request
    std::string task_type = analyzeDevelopmentTask(input);

    // Generate system prompt with mandate
    std::string system_prompt = getSystemPrompt();

    // Process the request based on task type
    std::string response;

    if (task_type == "implementation") {
      response = handleImplementationRequest(input);
    } else if (task_type == "refactoring") {
      response = handleRefactoringRequest(input);
    } else if (task_type == "bug_fix") {
      response = handleBugFixRequest(input);
    } else if (task_type == "architecture") {
      response = handleArchitectureRequest(input);
    } else {
      response = handleGeneralDevRequest(input);
    }

    // Validate code quality if response contains code
    if (containsCode(response)) {
      auto code_validation = behavior_policy_.validateCode(extractCode(response), "cpp");

      if (!code_validation.is_compliant) {
        // Add quality warnings
        response += "\n\n[CODE QUALITY ISSUES DETECTED]\n";
        response += code_validation.suggestion;
      }
    }

    return response;
  }

  void initializeBehaviorPolicy() override {
    // Strict configuration for development tasks
    VersaAI::BehaviorPolicy::PolicyConfig config;
    config.allow_placeholders = false;
    config.allow_todos = false;
    config.allow_simplifications = false;
    config.enforce_error_handling = true;
    config.enforce_documentation = true;
    config.enforce_production_quality = true;
    config.minimum_severity_to_reject = VersaAI::BehaviorPolicy::ViolationSeverity::HIGH;

    behavior_policy_.setConfig(config);
  }

private:
  std::string analyzeDevelopmentTask(const std::string& input) const {
    // Analyze input to determine task type
    std::string lower_input = toLower(input);

    if (lower_input.find("implement") != std::string::npos ||
        lower_input.find("create") != std::string::npos ||
        lower_input.find("build") != std::string::npos) {
      return "implementation";
    }

    if (lower_input.find("refactor") != std::string::npos ||
        lower_input.find("improve") != std::string::npos ||
        lower_input.find("optimize") != std::string::npos) {
      return "refactoring";
    }

    if (lower_input.find("fix") != std::string::npos ||
        lower_input.find("bug") != std::string::npos ||
        lower_input.find("error") != std::string::npos) {
      return "bug_fix";
    }

    if (lower_input.find("design") != std::string::npos ||
        lower_input.find("architecture") != std::string::npos ||
        lower_input.find("structure") != std::string::npos) {
      return "architecture";
    }

    return "general";
  }

  std::string handleImplementationRequest(const std::string& input) const {
    std::stringstream response;

    response << "Implementing complete, production-grade solution:\n\n";
    response << "[MANDATE ENFORCEMENT ACTIVE]\n";
    response << "- Complete implementation (no placeholders)\n";
    response << "- Comprehensive error handling\n";
    response << "- Full documentation\n";
    response << "- Optimal algorithms\n";
    response << "- Thread-safe where applicable\n\n";

    response << "Processing request: " << input << "\n\n";
    response << "[Implementation would be generated by underlying model with mandate constraints]\n";

    return response.str();
  }

  std::string handleRefactoringRequest(const std::string& input) const {
    std::stringstream response;

    response << "Refactoring to production standards:\n\n";
    response << "[MANDATE: No shortcuts - solve root causes]\n";
    response << "- SOLID principles applied\n";
    response << "- Optimal design patterns\n";
    response << "- Performance considerations\n";
    response << "- Maintainability improvements\n\n";

    response << "Processing request: " << input << "\n\n";

    return response.str();
  }

  std::string handleBugFixRequest(const std::string& input) const {
    std::stringstream response;

    response << "Fixing root cause (no workarounds):\n\n";
    response << "[MANDATE: Solve root cause, not symptoms]\n";
    response << "- Trace to root cause\n";
    response << "- Fix underlying issue\n";
    response << "- Add regression tests\n";
    response << "- Refactor if design flaw detected\n\n";

    response << "Processing request: " << input << "\n\n";

    return response.str();
  }

  std::string handleArchitectureRequest(const std::string& input) const {
    std::stringstream response;

    response << "Designing production-grade architecture:\n\n";
    response << "[MANDATE: Expert-level design from start]\n";
    response << "- Scalability considered\n";
    response << "- SOLID principles\n";
    response << "- Extensibility planned\n";
    response << "- Industry best practices\n\n";

    response << "Processing request: " << input << "\n\n";

    return response.str();
  }

  std::string handleGeneralDevRequest(const std::string& input) const {
    std::stringstream response;

    response << "Processing development request with production standards:\n\n";
    response << behavior_policy_.getMandatePrinciples() << "\n\n";
    response << "Request: " << input << "\n\n";

    return response.str();
  }

  bool containsCode(const std::string& text) const {
    // Simple heuristic to detect code blocks
    return text.find("```") != std::string::npos ||
           text.find("class ") != std::string::npos ||
           text.find("void ") != std::string::npos ||
           text.find("#include") != std::string::npos;
  }

  std::string extractCode(const std::string& text) const {
    // Extract code from markdown code blocks
    size_t start = text.find("```");
    if (start == std::string::npos) {
      return text;  // No code block, return full text
    }

    start = text.find('\n', start) + 1;  // Skip language identifier
    size_t end = text.find("```", start);

    if (end == std::string::npos) {
      return text.substr(start);
    }

    return text.substr(start, end - start);
  }

  std::string toLower(const std::string& str) const {
    std::string result = str;
    std::transform(result.begin(), result.end(), result.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    return result;
  }
};
